<?php

namespace JiraConnect\Controller;

use JiraConnect\Atlassian\FieldHelper;
use JiraConnect\Core\ControllerCore;
use JiraConnect\Core\Registerer;
use WPCF7_FormTag;
use WPCF7_TagGenerator;

class DescriptionChanger extends ControllerCore {
    private $fieldHelper;

    /**
     * DescriptionChanger constructor.
     *
     * @param Registerer $registerer
     * @param FieldHelper $fieldHelper
     * @uses SelectFieldType::wpcf7_init()
     */
    public function __construct(Registerer $registerer, FieldHelper $fieldHelper) {
        $this->fieldHelper = $fieldHelper;
        $registerer->add_action('wpcf7_init', $this);
	    $registerer->add_action('wpcf7_admin_init', $this);
    }


    public function wpcf7_init() {
        wpcf7_add_form_tag(['descriptionchanger'], [$this, 'custom_double_form_tag_handler'], ['name-attr' => true]);
    }

	public function wpcf7_admin_init() {
		$tag_generator = WPCF7_TagGenerator::get_instance();
		$tag_generator->add('jira_description', 'jira description', [$this, 'wpcf7_tag_generator_jira_description']);
	}


	function custom_double_form_tag_handler($tag) {
        global $wp;
        $pagePath =  $_SERVER['REQUEST_URI'];
        return '<input type="hidden" name="jira_description" value="'.$this->url().$pagePath.'">';
    }


    function url(){
        if(isset($_SERVER['HTTPS'])){
            $protocol = ($_SERVER['HTTPS'] && $_SERVER['HTTPS'] != "off") ? "https" : "http";
        }
        else{
            $protocol = 'http';
        }
        return $protocol . "://" . $_SERVER['HTTP_HOST'];
    }



	public function wpcf7_tag_generator_jira_description($contact_form, $args = '') {
		$args = wp_parse_args($args, array());
		$type = $args['id'];
		?>
		<div class="control-box">
			<fieldset>
				<legend>Jira Description Changer - generated by Jira Connect</legend>
				Jira Description Changer changes the content of the "description" field to the link to the job offer.
			</fieldset>
		</div>

		<div class="insert-box">
			<input type="text" name="<?php echo $type; ?>" class="tag code" readonly="readonly" value="[descriptionchanger]"/>

			<div class="submitbox">
				<input type="button" class="button button-primary insert-tag"
				       value="<?php echo esc_attr(__('Insert Tag', 'contact-form-7')); ?>"/>
			</div>

			<br class="clear"/>

			<p class="description mail-tag"><label
					for="<?php echo esc_attr($args['content'] . '-mailtag'); ?>"><?php echo sprintf(esc_html(__("To use the value input through this field in a mail field, you need to insert the corresponding mail-tag (%s) into the field on the Mail tab.", 'contact-form-7')), '<strong><span class="mail-tag"></span></strong>'); ?>
					<input type="text" class="mail-tag code hidden" readonly="readonly"
					       id="<?php echo esc_attr($args['content'] . '-mailtag'); ?>"/></label></p>
		</div>


		<?php
	}
}