<?php

namespace JiraConnect\Controller;

use JiraConnect\Atlassian\FieldHelper;
use JiraConnect\Core\ControllerCore;
use JiraConnect\Core\Registerer;
use WPCF7_FormTag;
use WPCF7_TagGenerator;

class LocationDetector extends ControllerCore
{
    private $fieldHelper;

    /**
     * DescriptionChanger constructor.
     *
     * @param Registerer $registerer
     * @param FieldHelper $fieldHelper
     * @uses SelectFieldType::wpcf7_init()
     */
    public function __construct(Registerer $registerer, FieldHelper $fieldHelper)
    {
        $this->fieldHelper = $fieldHelper;
        $registerer->add_action('wpcf7_init', $this);
        $registerer->add_action('wpcf7_admin_init', $this);

    }

    public function wpcf7_init()
    {
        wpcf7_add_form_tag(['locationdetector'], [$this, 'custom_double_form_tag_handler'], ['name-attr' => true]);
    }

	public function wpcf7_admin_init() {
		$tag_generator = WPCF7_TagGenerator::get_instance();
		$tag_generator->add('locationdetector', 'jira location', [$this, 'wpcf7_tag_generator_location']);
	}

    public function wpcf7_tag_generator_location($contact_form, $args = '') {
        $args = wp_parse_args($args, array());
        $type = $args['id'];
        ?>
        <div class="control-box">
            <fieldset>
                <legend>Jira Location Detector - generated by Jira Connect</legend>
                Jira Location Detector tries to detect the location of the job offer.
                <table class="form-table">
                    <tr>
                        <th scope="row">Location field: </th>
                        <td>
                            <select onchange="updateJiraLocation()" name="first-value" class="jira-cf7-location-select" >
                                <?php echo $this->fieldHelper->getOptions();?>
                                <input type="hidden" name="name" id="jira-cf7-location-name"/>
                            </select>
                        </td>
                    </tr>
                </table>
            </fieldset>
        </div>

        <div class="insert-box">
            <input type="text" name="<?php echo $type; ?>" class="tag code" readonly="readonly"
                   onfocus="this.select()"/>

            <div class="submitbox">
                <input type="button" class="button button-primary insert-tag"
                       value="<?php echo esc_attr(__('Insert Tag', 'contact-form-7')); ?>"/>
            </div>

            <br class="clear"/>

        </div>

        <script type="application/javascript">
            function updateJiraLocation() {
                var selectedValue = jQuery('.jira-cf7-location-select').children("option:selected").val();
                jQuery('#jira-cf7-location-name').val(selectedValue);
            }
        </script>

        <?php
    }


    function custom_double_form_tag_handler($tag)
    {
        $atts['name'] = $tag->name;
        return <<<HTML
<script>
jQuery( document ).ready(function() {
    var city = jQuery('.insights-filter-results__item__city').text().trim();
    var city = city.toString();
    var selector = "select[name='{$atts['name']}[0]'] option:contains('" + city +"')";
    if(jQuery(selector).length > 0){
        jQuery(selector).attr('selected', 'selected');
        jQuery("select[name='{$atts['name']}[0]']").hide();
    }
});
</script>
HTML;

    }


}