<?php

namespace JiraConnect\Controller;

use JiraConnect\Atlassian\FieldHelper;
use JiraConnect\Atlassian\OAuthFactory;
use JiraConnect\Core\ControllerCore;
use JiraConnect\Core\Registerer;
use WPCF7_TagGenerator;

class TagGenerator extends ControllerCore {
	private $oauth;
	private $fieldHelper;

	/**
	 * CF7 constructor.
	 *
	 * @param OAuthFactory $oauth
	 * @param Registerer $registerer
	 *
	 * @param FieldHelper $fieldHelper
	 *
	 * @uses wpcf7_editor_panels()
     * @uses wpcf7_admin_init()
	 */
	public function __construct(OAuthFactory $oauth, Registerer $registerer, FieldHelper $fieldHelper) {
		$this->fieldHelper = $fieldHelper;
		$this->oauth = $oauth;
		//$registerer->add_filter('wpcf7_editor_panels', $this);
		$registerer->add_action('wpcf7_admin_init', $this);
	}


	/**
     * @uses wpcf7_tag_generator_jira()
     * @uses wpcf7_tag_generator_jira_project()
        * @uses wpcf7_tag_generator_jira_summary()
	 */
	public function wpcf7_admin_init() {
		$tag_generator = WPCF7_TagGenerator::get_instance();
		$tag_generator->add('jira', 'jira field', [$this, 'wpcf7_tag_generator_jira']);

		$tag_generator->add('jira_project', 'jira project', [$this, 'wpcf7_tag_generator_jira_project']);

		$tag_generator->add('hidden', 'jira summary', [$this, 'wpcf7_tag_generator_jira_summary']);
	}

	/**
	 * @param $panels
	 * @return mixed
	 * @uses generator_panel_callback()
	 */
	public function wpcf7_editor_panels($panels) {
		$generator = [
			'generator-panel' => array(
				'title' => 'Generator',
				'callback' => [$this, 'generator_panel_callback'],
			)
		];

		return $generator + $panels;
	}

	public function generator_panel_callback($post) {
		echo '<p>Jira Fields</p>';
		$chk = [];
		foreach (get_option('jira_connect_base', []) as $key => $field) {
			echo '<div class="row">';
			echo '<div class="">';
			echo "<input " . ((isset($chk[ $key ]) && ($chk[ $key ] === "on")) ? "checked='checked'" : '') . " type='checkbox' name='chk[$key]' style='width: 1em; height: 1em;'/>";
			echo "</div>";
			echo '<div class="col-xs-11">';
			echo $field['name'] . "<br>";
			//echo "<input type='checkbox' name='add_to_form' value='".$field['name']."'>";
			if (is_array($field['schema']) && !empty($field['schema'])) {
				if (!empty($field['schema']['type'])) {
					echo $field['schema']['type'] . " - ";
				}
				if (!empty($field['schema']['customId'])) {
					echo $field['schema']['customId'] . " - ";
				}
				/*if (!empty($field['schema']['custom'])) {
					echo $field['schema']['custom'];
				}*/
				if (!empty($field['fieldId'])) {
					echo $field['fieldId'];
				}
				echo "<br>";
			}
			if (!empty($field['operations']) && is_array($field['operations'])) {
				echo 'Operations: ' . implode(', ', $field['operations']) . "<br>";
			}
			if (!empty($field['allowedValues']) && is_array($field['allowedValues'])) {
				echo 'allowedValues: ' . implode(', ', array_column($field['allowedValues'], 'value')) . "<br>";
			}
			echo "<br><br>";
			echo "</div>";
			echo "</div>";
		}
	}

	public function wpcf7_tag_generator_jira_summary($contact_form, $args = '') {
	    $args = wp_parse_args($args, array());
		$type = $args['id'];
	    ?>
	    <div class="control-box">
	        <fieldset>
	            <legend>Jira Summary - generated by Jira Connect</legend>
	            <table class="form-table">
	                <tr>
	                    <th scope="row">First Name: </th>
	                    <td>
	                        <select onchange="updateJiraSummary()" name="first-value" class="jira-cf7-first-value" >
	                            <?php echo $this->fieldHelper->getOptions();?>
	                        </select>
	                    </td>
	                </tr>
	                <tr>
	                    <th scope="row">Last name: </th>
	                    <td>
	                        <select onchange="updateJiraSummary()" name="second-value" class="jira-cf7-second-value" >
	                            <?php echo $this->fieldHelper->getOptions();?>
	                        </select>
	                        <input type="text" name="name" class="oneline" value="jira_summary default:" hidden="hidden"/>
	                        <input type="text" name="values" class="oneline jira-cf7-summary" id="<?php echo esc_attr( $args['content'] . '-values' ); ?>" hidden="hidden"/>
	                    </td>
	                </tr>
                </table>
            </fieldset>
	    </div>

        <div class="insert-box">
            <input type="text" name="<?php echo $type; ?>" class="tag code" readonly="readonly"
                   onfocus="this.select()"/>

            <div class="submitbox">
                <input type="button" class="button button-primary insert-tag"
                       value="<?php echo esc_attr(__('Insert Tag', 'contact-form-7')); ?>"/>
            </div>

            <br class="clear"/>

            <p class="description mail-tag"><label
                        for="<?php echo esc_attr($args['content'] . '-mailtag'); ?>"><?php echo sprintf(esc_html(__("To use the value input through this field in a mail field, you need to insert the corresponding mail-tag (%s) into the field on the Mail tab.", 'contact-form-7')), '<strong><span class="mail-tag"></span></strong>'); ?>
                    <input type="text" class="mail-tag code hidden" readonly="readonly"
                           id="<?php echo esc_attr($args['content'] . '-mailtag'); ?>"/></label></p>
        </div>

        <script type="application/javascript">
            function updateJiraSummary() {
                jQuery('.jira-cf7-summary').val(
                    jQuery('.jira-cf7-first-value').val() + ',' + jQuery('.jira-cf7-second-value').val()
                )
            }
        </script>

	    <?php
	}

	public function wpcf7_tag_generator_jira_project(){
	    ?>
        <div class="control-box">
            <fieldset>
                <legend>Jira Project - generated by Jira Connect</legend>
                <table class="form-table">
                    <tr>
                        <td>Project name: </td>
                        <td><strong><?php echo get_option('jira_projectKey') ?></strong></td>
                    </tr>
                    <tr>
                        <td>Issue Type:</td>
                        <td><strong><?php echo get_option('jira_IssueTypeKey') ?></strong></td>
                    </tr>
                </table>
            </fieldset>
            <br><br>
            <div class="insert-box">
                <input type="text" name="projectId" class="tag code" readonly="readonly"
                    value='[hidden jira_projectId default:"<?php echo get_option('jira_projectId'); ?>"][hidden jira_IssueTypeId default:"<?php echo get_option('jira_IssueTypeId'); ?>"]'/>
                <div class="submitbox">
                <input type="button" class="button button-primary insert-tag"
                       value="<?php echo esc_attr(__('Insert Tag', 'contact-form-7')); ?>"/>
                 </div>
            </div>
        <?php
    }

	public function wpcf7_tag_generator_jira($contact_form, $args = '') {
		$args = wp_parse_args($args, array());
		$type = $args['id'];
		?>
        <div class="control-box">
            <fieldset>
                <legend>Jira Fields - generated by Jira Connect</legend>

                <table class="form-table">
                    <tbody>

                    <!--
                    <tr>
						<th scope="row"><?php echo esc_html(__('Field type', 'contact-form-7')); ?></th>
						<td>
							<fieldset>
								<legend class="screen-reader-text"><?php echo esc_html(__('Field type', 'contact-form-7')); ?></legend>
								<label><input type="checkbox" name="required" /> <?php echo esc_html(__('Required field', 'contact-form-7')); ?></label>
							</fieldset>
						</td>
					</tr>
					-->

                    <tr>
                        <th scope="row"><label for="<?php echo esc_attr($args['content'] . '-name'); ?>">Jira
                                Field</label></th>
                        <td>
							<select onchange="updateJiraTab();" name="name" class="jira-cf7-name-select" id="<?php echo esc_attr($args['content'] . '-name'); ?>">
							    <?php echo $this->fieldHelper->getOptions(); ?>
							</select>
                            <input type="hidden" name="name" id="jira-cf7-name-trigger"/>
                        </td>
                    </tr>

                    <tr>
                        <th scope="row"><?php echo esc_html(__('Field type', 'contact-form-7')); ?></th>
                        <td>
                            <fieldset>
                                <legend class="screen-reader-text"><?php echo esc_html(__('Field type', 'contact-form-7')); ?></legend>
                                <select onchange="updateJiraType();" id="panel-jira-tagtype" class="jira-cf7-type-select" name="tagtype">
                                    <option value="" selected="selected">Wybierz:</option>
                                    <option value="text">Text</option>
                                    <option value="number">Number</option>
                                    <option value="email">E-mail</option>
                                    <option value="tel">Telephone</option>
                                    <option value="acceptance">Acceptance</option>
	                                <option value="file">File</option>
                                    <option value="select">Static drop-down</option>
                                    <option value="jirafield">Jira drop-down</option>
                                    <option value="hidden">Hidden</option>
                                </select>
                            </fieldset>
                            <fieldset>
                                <legend class="screen-reader-text"><?php echo esc_html(__('Field type', 'contact-form-7')); ?></legend>
                                <label><input type="checkbox" name="required"/> <?php echo esc_html(__('Required field', 'contact-form-7')); ?>
                                </label>
                            </fieldset>
                        </td>
                    </tr>


                    <!--<tr>
						<th scope="row"><label for="<?php echo esc_attr($args['content'] . '-values'); ?>"><?php echo esc_html(__('Default value', 'contact-form-7')); ?></label></th>
						<td>
                            <input disabled="disabled" type="text" name="values" class="oneline" id="<?php echo esc_attr($args['content'] . '-values'); ?>" /><br />
							!-- <label><input type="checkbox" name="placeholder" class="option" /> <?php echo esc_html(__('Use this text as the placeholder of the field', 'contact-form-7')); ?></label> --
                        </td>
					</tr> -->


                    <tr style="display: none">
                        <th scope="row"><?php echo esc_html(__('Options', 'contact-form-7')); ?></th>
                        <td>
                            <fieldset>
                                <legend class="screen-reader-text"><?php echo esc_html(__('Options', 'contact-form-7')); ?></legend>
                                <textarea name="values" class="values" style="display: none"
                                          id="<?php echo esc_attr($args['content'] . '-values'); ?>"></textarea>
                                <textarea disabled="disabled" name="values2" class="values2" style="display: none"
                                          id="<?php echo esc_attr($args['content'] . '-values2'); ?>"></textarea>
                                <label for="<?php echo esc_attr($args['content'] . '-values'); ?>"><span
                                            class="description"><?php echo esc_html(__("One option per line.", 'contact-form-7')); ?></span></label><br/>
                                <!--<label><input type="checkbox" name="multiple" class="option" /> <?php echo esc_html(__('Allow multiple selections', 'contact-form-7')); ?></label><br />
                                <label><input type="checkbox" name="include_blank" class="option" /> <?php echo esc_html(__('Insert a blank item as the first option', 'contact-form-7')); ?></label>-->
                            </fieldset>
                        </td>
                    </tr>


					<?php if (in_array($type, array('text', 'email', 'url'))) : ?>
                        <tr>
                            <th scope="row"><?php echo esc_html(__('Akismet', 'contact-form-7')); ?></th>
                            <td>
                                <fieldset>
                                    <legend class="screen-reader-text"><?php echo esc_html(__('Akismet', 'contact-form-7')); ?></legend>

									<?php if ('text' == $type) : ?>
                                        <label>
                                            <input type="checkbox" name="akismet:author" class="option"/>
											<?php echo esc_html(__("This field requires author's name", 'contact-form-7')); ?>
                                        </label>
									<?php elseif ('email' == $type) : ?>
                                        <label>
                                            <input type="checkbox" name="akismet:author_email" class="option"/>
											<?php echo esc_html(__("This field requires author's email address", 'contact-form-7')); ?>
                                        </label>
									<?php elseif ('url' == $type) : ?>
                                        <label>
                                            <input type="checkbox" name="akismet:author_url" class="option"/>
											<?php echo esc_html(__("This field requires author's URL", 'contact-form-7')); ?>
                                        </label>
									<?php endif; ?>

                                </fieldset>
                            </td>
                        </tr>
					<?php endif; ?>

                    <!-- <tr>
						<th scope="row"><label for="<?php echo esc_attr($args['content'] . '-id'); ?>"><?php echo esc_html(__('Id attribute', 'contact-form-7')); ?></label></th>
						<td><input type="text" name="id" class="idvalue oneline option" id="<?php echo esc_attr($args['content'] . '-id'); ?>" /></td>
					</tr>

					<tr>
						<th scope="row"><label for="<?php echo esc_attr($args['content'] . '-class'); ?>"><?php echo esc_html(__('Class attribute', 'contact-form-7')); ?></label></th>
						<td><input type="text" name="class" class="classvalue oneline option" id="<?php echo esc_attr($args['content'] . '-class'); ?>" /></td>
					</tr> -->

                    </tbody>
                </table>
            </fieldset>
        </div>

        <div class="insert-box">
            <input type="text" name="<?php echo $type; ?>" class="tag code" readonly="readonly"
                   onfocus="this.select()"/>

            <div class="submitbox">
                <input type="button" class="button button-primary insert-tag"
                       value="<?php echo esc_attr(__('Insert Tag', 'contact-form-7')); ?>"/>
            </div>

            <br class="clear"/>

            <p class="description mail-tag"><label
                        for="<?php echo esc_attr($args['content'] . '-mailtag'); ?>"><?php echo sprintf(esc_html(__("To use the value input through this field in a mail field, you need to insert the corresponding mail-tag (%s) into the field on the Mail tab.", 'contact-form-7')), '<strong><span class="mail-tag"></span></strong>'); ?>
                    <input type="text" class="mail-tag code hidden" readonly="readonly"
                           id="<?php echo esc_attr($args['content'] . '-mailtag'); ?>"/></label></p>
        </div>

        <script type="application/javascript">
            function updateJiraType() {
                let type = jQuery('#TB_window .jira-cf7-type-select option:selected');
                let values = jQuery('#tag-generator-panel-jira-values');
                let values2 = jQuery('#tag-generator-panel-jira-values2');
                if(type.val() === 'select') {
                    values.prop('disabled', false).val(values2.val()).show().parents('tr').show();
                    values2.prop('disabled', true).hide();
                } else if(type.val() === 'jirafield') {
                    values.prop('disabled', false).val('');
                    updateJiraTab();
                } else {
                    values2.prop('disabled', true).hide();
                    values.prop('disabled', false).val('').hide().parents('tr').hide();
                }
            }
            function updateJiraTab() {
                let selected = jQuery('#TB_window .jira-cf7-name-select option:selected');
                jQuery.post(ajaxurl, {
                    'action': 'jira_fields',
                    'field_id': selected.val(),
                }, function(response) {
                    let data = JSON.parse(response);
                    let values = jQuery('#tag-generator-panel-jira-values');
                    let values2 = jQuery('#tag-generator-panel-jira-values2');
                    if(data.type) {
                        jQuery('#panel-jira-tagtype').val(data.type);
                    }
                    values2.prop('disabled', true).val('').hide();
                    values.prop('disabled', false).val('').hide().parents('tr').hide();
                    if(typeof data.allowedValues === 'object' && data.allowedValues.length) {
                        if(data.type==='jirafield') {
                            values2.prop('disabled', true).val(data.allowedValues.join('\n')).show().parents('tr').show();
                            values.prop('disabled', false).val('').hide();
                        } else {
                            values.prop('disabled', false).val(data.allowedValues.join('\n')).show().parents('tr').show();
                        }
                    }
                    jQuery('#jira-cf7-name-trigger').val(selected.val()).change();
                });
            }
        </script>

		<?php
	}


}